server.port=8092
server.servlet.context-path=/property-view

spring.profiles.default=h2

spring.application.name=hotel

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:/liquibase/db.changelog-master.yaml

spring.jpa.hibernate.ddl-auto=none

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.tagsSorter=alpha