CREATE TABLE hotel (
                       id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(255),
                       brand VARCHAR(255),
                       house_number INT,
                       street VARCHAR(255),
                       city VARCHAR(255),
                       country VARCHAR(255),
                       post_code VARCHAR(255),
                       phone VARCHAR(255),
                       email VARCHAR(255),
                       check_in VARCHAR(6),
                       check_out VARCHAR(6),
                       description VARCHAR(255)
);

CREATE TABLE amenity (
                         id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE hotel_amenity (
                               hotel_id INT,
                               amenity_id INT
);

ALTER TABLE hotel_amenity
    ADD CONSTRAINT fk_hotel_amenity_hotel
        FOREIGN KEY (hotel_id) REFERENCES hotel(id);

ALTER TABLE hotel_amenity
    ADD CONSTRAINT fk_hotel_amenity_amenity
        FOREIGN KEY (amenity_id) REFERENCES amenity(id);